drop table if exists Cards;

create table Cards (
    number int not null,
    name varchar(20) not null,
    -- For card 101, Rank/Limit D-70, this field is D
    rank varchar(2) not null,
    -- For card 101, Rank/Limit D-70, this field is 70
    limit
        int not null,
        description varchar(200) not null,
        -- Specified Slot / Unspecified Slot / Spell
        class varchar(15) not null,
        -- 2 letter short form: ex (SR) => Short Range
        spellType varchar(10),
        -- Cards each have a number thats unique to that card
        primary key (number)
);

-- Specified Slot Cards
insert into
    Cards (
        number,
        name,
        rank,
        limit
, description, class, spellType
    )
values
(0,'Rulers Blessing (Blessing of Ruler)','SS',1,'A castle given as a prize for winning the contest, town with population 10,000 included. Its residents will live according to whatever laws and commands you issue.','Specified Slot',null),
(1,'Patch of Forest (Area of Dense Forest)','SS',3,'The entrance to the giant forest called the Mountain Gods Garden where many unique endemic species live. They are all tame and friendly.','Specified Slot',null),
(2,'Plot of Beach (Strip of Beach)','SS',3,'The entrance to a cave called Poseidons Cavern. The cave changes its path at each visit, confusing intruders.','Specified Slot',null),
(3,'Pitcher of Eternal Water (Pot of Spring Water)','A',17,'A jar from which pure, clean water (1440 L per day) continually flows.','Specified Slot',null),
(4,'Skin Care Hot Springs (Beautiful Skin Spa)','A',15,'A hot spring that cures you of any skin condition. Bathing in it for half an hour a day gives you skin as soft and smooth as a babys.','Specified Slot',null),
(5,'Spirited Away Hollow (Cave of Mysterious Disappearance)','S',8,'Enter and then exit this hollow and you will be transported to a desolate location within the country. Circumstances will allow you to return to where you started without you having to spend any money.','Specified Slot',null),
(6,'Liquor Spring (Fountain of liquor birth)','A',15,'Draw some of this springs water and one hour later it will become a random alcoholic drink of exquisite taste and extraordinary quality.','Specified Slot',null),
(7,'Pregnancy Stones (Stones of the Pregnant)','S',10,'Carry a stone (weighing 7 lb. each) for one month and you will get pregnant, even if youre male. You may choose the sex of the baby by the female or male stone.','Specified Slot',null),
(8,'Mystery Pond (Mysterious Pond)','S',10,'Release one fish into this pond, and there will be one more fish of that type the next day. You can keep any combination of fish in this pond, even saltwater and freshwater fish together!','Specified Slot',null),
(9,'Tree of Plenty (Tree of Good Harvest)','S',20,'A tree that bears all sorts of fruit. No matter how much you harvest, it will be full again the next day. The type and number of fruit are random.','Specified Slot',null),
(10,'Golden Guidebook','A',20,'A travel guide that lists where and when you can meet people of the opposite sex who are your type.','Specified Slot',null),
(11,'Golden Scales (Golden Balance)','B',30,'When faced with a two-option choice, these scales will tell you which is better for your future.','Specified Slot',null),
(12,'Golden Dictionary','S',10,'Each day you will find a word glowing gold. You should learn those words because they will come in handy the next day.','Specified Slot',null),
(13,'Luck Bankbook (Good Luck Passbook)','A',20,'Refrain from using the little things of good luck in your daily life, and you can accumulate and convert them into cash.','Specified Slot',null),
(14,'Connection Severing Scissors (Edge-Cutting Scissors)','B',22,'Cut a picture of someone you dont want to see with these scissors, and you will never see them again. Caution: It will take effect on everyone in the picture (except yourself).','Specified Slot',null),
(15,'Fickle Genie (Whimsical Majin)','S',10,'This genie will grant you three wishes, but you need to suggest 1000 potential, significantly different wishes and he will choose three from among them. (No cheating by asking for different increments of money.)','Specified Slot',null),
(16,'Fairy Kings Advice (Advice King Fairy)','S',6,'The Fairy King offers you gentle, apt advice on what you lack or what you should fix. The annoying thing is he appears when he wants to.','Specified Slot',null),
(17,'Angels Breath','SS',3,'She cures one person of all wounds and ills, restoring them to perfect health. She will only appear once.','Specified Slot',null),
(18,'Imps Wink (Wink of this Devil)','A',18,'You will experience the most amazing ecstasy when she winks at you. She can appear multiple times. Be warned, it can get addictive.','Specified Slot',null),
(19,'Poltergeist Pillow (Spirits of the Dead Pillow)','A',13,'Sleep on this pillow and your astral form will be able to wander at will, but you will turn into a real ghost if you do not return to your body within 24 hours.','Specified Slot',null),
(20,'Mood Clock (Mind Spirit Meter)','B',30,'This clock sets your current state of mind. Turn it to noon and you will maintain perfect serenity. Thus you can adjust your emotions according to the situation.','Specified Slot',null),
(21,'X-Ray Goggles (Skeleton Spectacles)','B',27,'You can see through things. An adjustment dial allows you to set the x-ray depth. The only thing it cannot see through is a pack of spell cards from Masadora.','Specified Slot',null),
(22,'Toraemon','A',22,'A beast on the verge of extinction, it has a habit of stuffing things in its 4-D pocket. You never know what kind of treasures it could have picked up.','Specified Slot',null),
(23,'Tome of a Thousand Tales (Ad-lib Book)','B',30,'A book that shows you a different story each time you open it. If you want to stay on the same story when you put it down, use the special included bookmark.','Specified Slot',null),
(24,'Hypothetical T.V. (TV Moshimo)','A',20,'Input a hypothetical situation with the included remote, and this TV will show you a 30-hour documentary of the possibilities. You are also able to record.','Specified Slot',null),
(25,'Risky Dice (Risky Die)','B',30,'A twenty-sided die with one skull face and 19 star faces. Great things happen when you roll a star, but rolling the skull will be bad enough to cancel out all the previous great events.','Specified Slot',null),
(26,'Night Shift Dwarves (Seven Working Dwarves)','A',20,'They can do any work you can do, and they will work as long as you are asleep. They cannot do anything beyond your abilities.','Specified Slot',null),
(27,'Book of V.I.P Passes (Face Path Tickets)','B',25,'You can go anywhere with these passes. Book of 1000.','Specified Slot',null),
(28,'Capricious Remote','S',13,'A remote control to manipulate ten emotions someone feels toward someone else, on an intensity scale of 1-10. (You cannot control how people feel toward you.)','Specified Slot',null),
(29,'Pre-Order Vouchers (Forced Reservation Tickets)','B',27,'Write the name of any commercially available product on a voucher and youll be guaranteed to get it regardless of its scarcity (You still have to pay). A book of 1000.','Specified Slot',null),
(30,'Favor Cushion (Connection Cushion)','B',21,'Seat someone on this cushion and he will do one thing for you, so long as it is within his capabilities.','Specified Slot',null),
(31,'Double Postcard to the Dead (Return Postcard to the Dead)','S',13,'Address and mail this return postage-paid postcard to a deceased person, and you will get a reply the next day. A book of 1000.','Specified Slot',null),
(32,'Parrot Candy','B',30,'Sucking on this candy enables you to produce any voice. The effect lasts until you next ingest something. A set of 10 packs, 50 candies per pack.','Specified Slot',null),
(33,'Hormone Cookies (Cookie Hormones)','S',13,'After eating this candy, your sex will temporarily change for 24 hours. A set of 10 boxes; 20 cookies per box.','Specified Slot',null),
(34,'University Survey (Anything Questionnaire)','B',30,'Write various questions pertaining to yourself and give it to someone, and he will answer all questions honestly. Reusable.','Specified Slot',null),
(35,'Chameleon Cat','S',6,'An endangered species. Once tamed, it can transform into any animal. However, its mass remains constant, so it will be a tiny elephant or a large hamster, for example.','Specified Slot',null),
(36,'Recycling Room (The Recycle Room)','S',10,'Put something broken in this room and it will be repaired as good as new 24 hours later. The door must not be opened until time is up.','Specified Slot',null),
(37,'Fledgling Athlete (Egg of Superb Athlete)','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top athlete when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(38,'Fledgling Artist (Egg of Superb Artist)','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top artist when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(39,'Fledgling Politician (Egg of Big-Shot Politician)','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top politician when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(40,'Fledgling Musician (Egg of Superb Musician)','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top musician when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(41,'Fledgling Pilot (Egg of Superb Pilot)','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top pilot when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(42,'Fledgling Novelist (Egg of Superb Writing)','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top novelist when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(43,'Fledgling Gambler (Egg of Major Gambler)','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top gambler when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(44,'Fledgling Actor','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top actor when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(45,'Fledgling CEO','B',30,'Warm this magic egg in your hand for three hours a day for one to ten years, and you will become a top CEO when it hatches. The stronger your desire during incubation, the sooner it will hatch.','Specified Slot',null),
(46,'Gold Dust Girl','A',13,'A girl who sheds gold dust from her body—500g of gold can be harvested from her daily bath. Very shy, she rarely leaves the house.','Specified Slot',null),
(47,'Sleeping Girl','A',11,'A girl who sleeps in your stead. You can be active for 24 hours without sleeping while she sleeps for you.','Specified Slot',null),
(48,'Aromatherapy Girl','A',15,'A girl who emits the most comfortable aroma for you. While shes by your side, you will be free of stress.','Specified Slot',null),
(49,'Miniature Mermaid','B',23,'A mermaid small enough to fit in your hand. A comfortable living environment puts her in a good mood, and she will sing with her beautiful voice.','Specified Slot',null),
(50,'Miniature Dino','A',11,'A dinosaur small enough to fit in your hand. This creature produces a different species of tiny dinosaur with each new generation.','Specified Slot',null),
(51,'Miniature Dragon','S',10,'A dragon small enough to fit in your hand. It will obey your commands, and will eventually learn to talk if raised with love.','Specified Slot',null),
(52,'Pearl Locusts','B',30,'Each of these locusts has a pearl in its abdomen. An outbreak occurs once every dozen years or so.','Specified Slot',null),
(53,'King Great White Beetle','A',30,'It uses special pheromones to lure other insects to build a huge colony. It leaves the colony once a day for an evening stroll.','Specified Slot',null),
(54,'Millennium Butterfly','A',25,'A legendary insect named from the fact that the family of anyone who captures it will prosper for generations.','Specified Slot',null),
(55,'Revenge Shop','A',20,'Report your grudges to the manager and he will retaliate for you in proportion to your grievance. Pay extra to request a more severe retaliation.','Specified Slot',null),
(56,'Perfect Memory Studio','B',25,'Specify a time and date to get a picture of yourself in the past. You may also request a sequence of photographs.','Specified Slot',null),
(57,'Hideout Realtor','A',11,'The agent will build a secret room just for you at a place of your choosing. However, you must not tell anyone about it or bring anybody to it.','Specified Slot',null),
(58,'Secrets Video Rental','A',13,'Rent videos of other peoples secrets. You must not show the video or discuss its contents with anyone.','Specified Slot',null),
(59,'Instant Foreign Language School','A',20,'Spend time studying a language at this school, and you will accrue time on a timer (included). While the timer is activated and counting down, you will be fluent.','Specified Slot',null),
(60,'Long Lost Delivery','B',30,'Call the number and describe the item you lost, and it will be delivered to you the next day. It must be lost for longer than a month.','Specified Slot',null),
(61,'Vending Check-Up','A',20,'A full-body medical scan for just 500. However, the only results are All Clear or Anomaly Detected, in which case it is recommended you see a doctor.','Specified Slot',null),
(62,'Club You Rule','B',20,'Everyone in the club will do your bidding while you are there. However, one hour in the club equals a day outside.','Specified Slot',null),
(63,'Virtual Restaurant','B',30,'You can order any food you want. You will feel full, but it is only an illusion. You will be given a multivitamin as you leave.','Specified Slot',null),
(64,'Witchs Love Potion','B',30,'Kiss a pill and have your intended drink it, and he or she will fall in love with you. One pill lasts one week; one vial contains 500 pills.','Specified Slot',null),
(65,'Witchs Rejuvenation Potion','S',10,'Each pill makes you physically younger by one year. You will retain all knowledge and memories. Beware, as you will die if you take more than your age. One vial contains 100 pills.','Specified Slot',null),
(66,'Witchs Diet Pills','B',28,'Each pill makes you lose one kg. One vial contains 200 pills. Beware, as you will die if you take more than you weigh.','Specified Slot',null),
(67,'Doyens Growth Pills','B',30,'Each pill makes you grow one cm taller. One vial contains 100 pills. Not recommended for people under 20 years of age.','Specified Slot',null),
(68,'Doyens Virility Pills','A',20,'A certain part of your anatomy will get very frisky. Both endurance and frequency are enhanced. One vial contains 500 pills.','Specified Slot',null),
(69,'Doyens Hair Restorer','B',30,'Luxurious hair will grow wherever it is applied. Use gloves, or hair will grow on fingers and palms. One vial contains 200 ml (enough to cover ten heads).','Specified Slot',null),
(70,'Mad Scientists Steroids','A',16,'Get all the muscles you want without exercise. You must drink a liter a day for a week, and it tastes horrible. A seven-box set, with ten one-L bottles per box.','Specified Slot',null),
(71,'Mad Scientists Pheromones','A',20,'Spray on your body to attract the opposite sex. However, you cannot adjust the strength of its effect, so be careful as it may cause a proliferation of stalkers.','Specified Slot',null),
(72,'Mad Scientists Plastic Surgery','A',15,'Scan a picture of the face you want and you will end up an exact likeness. Each surgery carries a 5% chance of failure, and a 1% chance the machine itself will break.','Specified Slot',null),
(73,'Night Jade','A',15,'A jewel blessed by the Devil. When danger is about to befall its owner, it will deflect it to someone else.','Specified Slot',null),
(74,'Sages Aquamarine','A',15,'Its owner will have many intelligent friends and keep those friendships for their entire lives.','Specified Slot',null),
(75,'Wild Luck Alexandrite','A',20,'Its owner will get to have once-in-a-lifetime experiences, though you cannot choose whether theyre for better or for worse...','Specified Slot',null),
(76,'Roaming Ruby','B',30,'The owner of this ruby will gain immense wealth, but will never be able to remain in the same place for more than a week.','Specified Slot',null),
(77,'Beauty Magnet Emerald','S',10,'Specialists offering beauty services will flock to its owner, who will shine with heretofore unrecognized beauty.','Specified Slot',null),
(78,'Lonely Sapphire','B',30,'The owner of this sapphire will acquire vast wealth, but in exchange will spend a lifetime alone, forsaken by friends, family, and significant others.','Specified Slot',null),
(79,'Rainbow Diamond','A',20,'A diamond that shines in a rainbow of colors. Propose with this diamond and she is guaranteed to say yes.','Specified Slot',null),
(80,'Levitation Stone','S',7,'A stone about one carat in size that levitates. It can levitate one person, and receives energy from sunlight.','Specified Slot',null),
(81,'Blue Planet','SS',5,'A unique blue jewel. Its composition does not correspond to any known mineral, so it was given this name to mean a gift from space.','Specified Slot',null),
(82,'Staff of Judgment','A',15,'Raise this staff in the air while calling out the name of someone you want to punish, and calamity will befall the one of you who has committed more bad deeds, the target or yourself.','Specified Slot',null),
(83,'Sword of Truth','B',22,'Splits in two anything and anyone deceitful. In trials, its a criminals worst nightmare. The sword will shatter when used to cut something true, but will regenerate if stored in its scabbard for one day.','Specified Slot',null),
(84,'Paladins Necklace','D',60,'A player wearing this will reflect curses cast upon him, and be able to undo curses placed on cards he touches.','Specified Slot',null),
(85,'Scapegoat/Sacrifice Armor','S',8,'Renders ineffective any attack by a weapon reverted from a card. Beware, as it will randomly break sometime within the first 100 attacks.','Specified Slot',null),
(86,'Quiver of Frustration','A',11,'You will be able to cast as many Leaves as you have arrows. It comes with 10 arrows, and one will be used each time you cast Leave.','Specified Slot',null),
(87,'Shield of Faith','S',15,'The spells Relegate, Return, Drift, and Collision will be rendered ineffective within a radius of 20 M of the player armed with this shield.','Specified Slot',null),
(88,'Eternal Hammer','A',15,'Anyone hit with this hammer will be afflicted with one random attack spell, and cannot defend him or herself with a defensive spell. However, it will not work on someone using Fortress or Paladins Necklace.','Specified Slot',null),
(89,'Tax Collectors Gauntlet','A',20,'Grants you the ability to cast Levy. However, it will destroy one random specified slot card from your binder every time. (You cannot cast it if your specified slots are empty.)','Specified Slot',null),
(90,'Memory Helmet','A',20,'You will never forget things you see or hear while wearing this helmet. Unfortunately, its extremely large and heavy.','Specified Slot',null),
(91,'Plastic King','A',20,'Recombine the parts of this 1:1 scale model kit to build any kind of vehicle. Fully functional, fuel not included.','Specified Slot',null),
(92,'Swap Ticket','S',7,'Rip the ticket and give it to someone you want to switch with, and you can live his life for 24 hours. Book of 1000.','Specified Slot',null),
(93,'Book of Life','B',28,'An encyclopedia of everyone whos been in your life since your birth, with records of conversations and memorable incidents. It may end up being tens of thousands of pages long.','Specified Slot',null),
(94,'Bandits Blade','S',10,'A successful attack with this weapon will cast Mug, Pickpocket, or Thief on the target. Not effective on someone using Fortress or Paladins Necklace.','Specified Slot',null),
(95,'Secret Cape','A',20,'You will be under the effect of Blackout Curtain while wearing this cape.','Specified Slot',null),
(96,'Clairvoyant Snake','A',12,'Feed it a card Rank C or above, and it will spit up a Clairvoyance.','Specified Slot',null),
(97,'3-D Camera','A',20,'Pictures taken with this will be developed as 3-D objects, with all textures reproduced. Make enlargements as needed.','Specified Slot',null),
(98,'Silver Dog','S',8,'An endangered species with silver fur. Mix 5g of gold into its food every day and it will excrete one kg of solid silver feces.','Specified Slot',null),
(99,'Panda Maid','S',8,'An endangered species. Very neat and loves to cook, and each has a hobby such as sewing or gardening. They are excellent at taking care of human children.','Specified Slot',null);


-- Unspecified Slot Cards
insert into
    Cards (
        number,
        name,
        rank,
        limit
, description, class, spellType
    )
values
(100,'Map of the Island empty','G',400,'A map of the island. No towns or markers are currently shown. The user will automatically fill these in on their travels.','Unspecified Slot',null),
(101,'Map of the Island detailed','D',70,'A detailed map of the island, with all towns and markers already shown.','Unspecified Slot',null),
(102,'Voucher','SS',150,'A special voucher which transforms into the card Angels Breath once one becomes available.','Unspecified Slot',null),
(110,'Rulers Invitation','SS',1,'A letter which extends a warm invitation to visit the games capital city, Limeiro. A visit to this citys castle is also included.','Unspecified Slot',null),
(163,'Sick Villagers','F',150,'These villagers are very sick.','Unspecified Slot',null),
(263,'Healthy Villagers','C',50,'These villagers are as healthy as can be!','Unspecified Slot',null),
(266,'Transport Ticket','B',150,'A ticket which allows the barer to use a safe passage out of the game.','Unspecified Slot',null),
(572,'Giant Cyclops','G',333,'These one-eyed giants are the largest of all Cyclops. They travel in small groups and attack anything within their territory.','Unspecified Slot',null),
(585,'Bubble Horse','C',50,'This hard-to-catch creature emits bubbles when threatened as a diversionary tactic. White bubbles will burst in contact with Aura. Red ones will burst with everything else except Aura.','Unspecified Slot',null),
(598,'Chief of Wolf Pack','C',45,'The leader of a wolf pack that attacks travelers.','Unspecified Slot',null),
(607,'J10,000','H',-2,'10,000  in card form.','Unspecified Slot',null),
(673,'Hyper Puffball','D',80,'This little creature is a fast fellow. They are a really fast, hard to catch species.','Unspecified Slot',null),
(697,'Melanin Lizard','E',100,'A very large lizard big enough to eat a cow whole.','Unspecified Slot',null),
(711,'Radio Rat','H',800,'These hard to catch creatures use aura to control a suit of armor. As a defensive measure, it uses this armor to mislead a target into thinking the armor is the enemy whilst the true creature can escape.','Unspecified Slot',null),
(1217,'Galgaida','F',185,'This fish when cooked, tastes delicious.','Unspecified Slot',null),
(7018,'Chidon','C',-1,'A fish. Debut in Chapter 172.','Unspecified Slot',null),
(-1,'Gold Dust Girl Guard','F',-1,'The guard is an NPC. He guarded the Gold Dust Girl.','Unspecified Slot',null),
(-2,'Cursed Statue of Lady Luck','Unknown',-1,'A reward in Antokiba. Debut in Chapter 129.','Unspecified Slot',null),
(14170,'Gasoline','H',-2,'A vial containing gasoline. This flammable substance will catch fire easily.','Unspecified Slot',null),
(21449,'Rock','H',-2,'A simple rock. Quite hard and can be any size.','Unspecified Slot',null),
(25008,'Large Rock','H',-2,'A large rock.','Unspecified Slot',null);

-- Spell Cards
insert into
    Cards (
        number,
        name,
        rank,
        limit
, description, class, spellType
    )
values
(1001,'Peek','G',200,'View contents of target players (previously met) free slots.','Spell','LR | RS'),
(1002,'Fluoroscopy','F',150,'View contents of target players (previously met) designated slots.','Spell','LR | RS'),
(1003,'Defensive Wall','G',400,'Protects you from an attack spell once.','Spell','SR | DS'),
(1004,'Reflect','E',120,'Reflects an attack spell from a player (previously met).','Spell','SR | DS'),
(1005,'Magnetic Force','C',50,'Allows one person to fly to the location of the target player.','Spell','LR | RS'),
(1006,'Pickpocket','F',170,'Steals a random card from target players free pocket.','Spell','SR | AS'),
(1007,'Thief','C',50,'Steals a random card from target players designated pocket.','Spell','SR | AS'),
(1008,'Trade','E',100,'Swaps a card the casters owns to a target players card randomly.','Spell','SR | AS'),
(1009,'Return','G',380,'Allows caster to fly back to a previously visited location.','Spell','LR | RS'),
(1010,'Mimic','A',20,'Transform a card into a copy of a target card that the caster already owns (it fails if target cards transformation limits is already exceeded)','Spell','SR | RS'),
(1011,'Clone','D',70,'Change into one random card from target players imposed slots (if the opponent has no imposed slot cards or the card limit was at MAX, the transformation fails and Clone disappears).','Spell','SR | RS'),
(1012,'Relegate','F',140,'Make the target player fly somewhere on the island.','Spell','SR | RS'),
(1013,'Origin','D',65,'Make target player fly to the game starting point.','Spell','SR | RS'),
(1014,'Leave','B',30,'Make target player leave the island.','Spell','SR | RS'),
(1015,'Clairvoyance','D',70,'See all card data of the target player.','Spell','LR | RS'),
(1016,'Drift','F',200,'Go to a random unvisited town. If all towns have been visited, player stays at the same place and the card disappears).','Spell','SR | RS'),
(1017,'Collision','F',200,'Fly to the locations of a random player the caster has not met (if all other players have been met, players stay at the same place and the card disappears).','Spell','SR | RS'),
(1018,'Levy','B',25,'Take one random card from each player within a 20m radius.','Spell','SR | RS'),
(1019,'Drawbridge','F',200,'Protect once against a short range regular spell from another player.','Spell','SR | DS | AA | VS'),
(1020,'Fake','C',40,'Fake transforms into one of the cards from No.001 to No.099. The resulting card can be inserted into an imposed slot but does not count towards a complete card set or the card copy limit, nor can it be converted into an object.','Spell','SR | RS'),
(1021,'Mug','B',30,'Take one card at will from target player.','Spell','SR | AS'),
(1022,'Corruption','C',40,'Transform one above-B ranked card from target player into a below-D card. The caster can choose the number of the new card. (After the transformation, the card counts towards the card number limit of the new card type. If the limit is already at MAX, or the target player has no above-B cards, the transformation fails and the “Corruption” card disappears). After the transformation, if the card is in an imposed slot with a wrong number, it auto-destroys.','Spell','SR | AS'),
(1023,'Compromise','B',25,'Choose and destroy one above-A ranked card from target player. That player then obtains a card of 3 ranks lower than the destroyed card and of the number of his choosing. If target player has no above-A card, “Compromise” changes into card form again and returns to the caster. (If the designated card of three ranks lower has attained the card copy limit, it cannot be obtained.)','Spell','SR | AS'),
(1024,'Dispel','D',80,'Return all cards from target player transformed with “Fake,” “Clone,” or “Mimic” to original form. Destroy all cards that, as a result, find themselves in the wrong imposed slots. “Fake,” “Copy,” and “Mimic” have no effect on “Dispel.”','Spell','SR | RS'),
(1025,'Blackout Curtain','F',200,'Use to protect oneself against the effects of Peek and Fluoroscopy.','Spell','SR | DS | C'),
(1026,'Holy Water','A',20,'Protects the player ten times from attack spells from other players. This card is immune to steal and destruction spells.','Spell','SR | DS | C'),
(1027,'Trace','E',90,'Current location of one target player will be available at all times. (Effect lasts until player leaves the game.)','Spell','SR | AS'),
(1028,'Rock Toss','E',100,'Destroy one random card in target players free slots.','Spell','SR | AS'),
(1029,'Bullet','B',25,'Destroy one random card in target players imposed slots.','Spell','SR | AS'),
(1030,'Guidepost','E',120,'Give away locations of the chosen number (not available to No. 000).','Spell','LR | RS'),
(1031,'Analysis','G',400,'Show explanation on card of the chosen number (not available to No. 000).','Spell','LR | RS'),
(1032,'Lottery','G',350,'Transform into a random item card.','Spell','SR | RS'),
(1033,'Cling','C',50,'Complete data of one players restricted slots will be available at all times. (Effect lasts until player leaves the game.)','Spell','SR | AS'),
(1034,'Purify','D',55,'Dispel effect of transformation spell and return card to original form. (If, after transformation, the card limit is exceeded, the card changes to item form and cannot be converted again. In the case of a spell card, it disappears unless the spell is used immediately.)','Spell','SR | RS'),
(1035,'Fortress','S',10,'Cards inserted in slots on target page are permanently protected against stealing and destruction spells as long as they remain in the slots (Free Slot pages cannot be chosen).','Spell','SR | DS | C | AA'),
(1036,'Eye of God','S',10,'Caster obtains the effects of List and Analysis permanently on all cards from No. 000 to 099. (Effect lasts until target player leaves the game.)','Spell','LR | C'),
(1037,'Recycle','F',170,'Allows an item converted from a card to be changed into card form once more. (Limited to cards of rank below C. If the applicable card limit is already at MAX, “Recycle” disappears without converting the target item.)','Spell','SR | RS'),
(1038,'List','G',350,'Inform on number of people in possession of target card, as well as the total number of copies.','Spell','LR | RS'),
(1039,'Accompany','F',130,'Fly all players within a radius of 20 m around the caster – including the caster – to the location of target city (limited to cities previously visited) or target player (limited to players previously met inside the game).','Spell','SR | RS'),
(1040,'Contact','F',200,'Allows communication through the binders with target player (limited to players previously met inside the game. Maximum duration is 3 minutes; during this period, only the player initiating conversation with “Contact” can cut off communication.)','Spell','LR | RS');

